### PR TITLE
Ijrah 42 changing configuration

### PR DESCRIPTION
**Pull request by jamesrichard91**
Updating the Ui based on Karen's comments

### CODE REVIEW

**Comment by jamesrichard91** [comment]
adjustedconfiguration

This is what the new configuration looks like. ( I adjusted some of the tables to fit in the screenshot )

**Comment by stevebillings** [comment]
Looks good

**Comment by psantos1113** [comment]
looks good

**Comment by ekerwin** [comment]
Nice!

**Pull request merged**
